from turtle import *

def draw_base():
    color("white")
    goto(100,-50)
    pendown()
    begin_fill()
    circle(10,360,4)
    end_fill()
    penup()
    color("black")
    goto(100,-30)
    write("1st",font=("Arial", 10), align="center")
    goto(0,0)
    color("white")
    goto(0,50)
    pendown()
    begin_fill()
    circle(10,360,4)
    end_fill()
    penup()
    color("black")
    goto(0,70)
    write("2nd",font=("Arial", 10), align="center")
    goto(0,0)
    color("white")
    goto(-100,-50)
    pendown()
    begin_fill()
    circle(10,360,4)
    end_fill()
    penup()
    color("black")
    goto(-100,-30)
    write("3rd",font=("Arial", 10), align="center")
    goto(0,0)


def pitcher():
    penup()
    goto(0,-55)
    write("Pitcher",font=("Arial", 11), align="center")
    goto(0,0)
   
def home_base():
    penup()
    goto(0,-177)
    color("white")
    begin_fill()
    left(45)
    pendown()
    forward(20)
    left(45)
    forward(10)
    left(90)
    forward(30)
    left(90)
    forward(10)
    penup()
    end_fill()
    color("black")
    goto(0,-150)
    write("Home",font=("Arial", 11), align="center")

draw_base()
pitcher()
home_base()
goto(-300,0)