from turtle import *

speed(0)
penup()
goto(0,-110)
pendown()
def bead_bracelet():
    for i in range (12):
        color("blue")
        begin_fill()
        circle(10)
        end_fill()
        left(10)
        penup()
        forward(20)
        pendown()
        color("red")
        begin_fill()
        circle(10)
        end_fill()
        left(10)
        penup()
        forward(20)
        pendown()
        color("purple")
        begin_fill()
        circle(10)
        end_fill()
        left(10)
        penup()
        forward(20)
        pendown()
bead_bracelet()

penup()
goto(-10,0)